version: '3.5'

services:
  meta-ms-projects-app:
    build:
      context: ${META_MS_PROJECTS_BASEPATH:-.}
      dockerfile: docker/node/Dockerfile
    container_name: meta-ms-projects-app
    image: meta-ms-projects-app
    ports:
      - ${META_MS_PROJECTS_PORT:-3000}:3000
    volumes:
      - ${META_MS_PROJECTS_BASEPATH:-.}/:/app/:delegated
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - meta-ms-db